# Generated by Django 4.0.10 on 2025-06-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exerpt',
            field=models.CharField(max_length=50),
        ),
    ]
