# Generated by Django 4.0.10 on 2025-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_exerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='posts/default.jpg', upload_to='posts/'),
        ),
    ]
